# Generated by Django 4.1.7 on 2023-03-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auth_user',
            table='user_profile',
        ),
    ]
