# Generated by Django 4.1.7 on 2023-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_balance_alter_portfolio_user_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_buy',
            field=models.BooleanField(default=True),
        ),
    ]
